### ISSUE TITLE
Instructions tell me to use .ihx file, but the flasher wants .hex or .bin (IOError)

### ISSUE THREAD

**Issue by MorgusLethe** [nepeee/TinyHawkFlyskyRx#3]
Hi, I am trying to follow the instructions in the README. I am flashing with a Raspberry Pi, so I am using the code from https://github.com/jimmyw/CC2510Lib
However, executing `python cc_write_flash.py main.ihx` throws an IOError: could not detect file format. Looking at the source code, this happens if the file is not .hex or .bin , which it isn't. There are no other .hex or .bin files in the repo either. I could convert the .ihx file to .hex, but I don't want to mess around to avoid bricking my TinyHawk.

Am I using the command correctly? Thanks for your help and this great project!

**Comment by MorgusLethe** [comment]
I just realized there is a "build" section in the README at the very end. It suggests that make.sh will build a .hex file, but it does not happen. Any further instructions?

The README could be better formatted, I will update it when I get things working 😄

**Comment by fishbonegaminglabs** [comment]
Just rename the file, can't remember exactly, in hex or bin and try again. If you look in the source code it will tell you which file extensions it actually accepts.

**Comment by MorgusLethe** [comment]
I have no experience with flashing, but isn't just changing the file extension quite risky? From the issues you posted I know that you successfully flashed your tinyhawk, so I will probably do it. But can you please explain why this will work? Thanks in advance :)

**Comment by MorgusLethe** [comment]
I did as you say, and it worked. Thanks. I will perhaps create a pull request to make this project a bit easier to follow.
